#!/bin/bash -eux


echo "DISCOURSE_DB_PASSWORD=123456" >> .env
echo "POSTGRES_PASSWORD=123456" >> .env
echo "NUM_WEBS=1" >> .env

mkdir -p ./data/{assets,uploads,backups}

docker-compose run app bash -c "sleep 60 && rake db:migrate assets:precompile"
docker-compose run app bash -c "rake admin:create"

echo "!!!Configure notification email in discourse settings!!!!!!"



